"""Prefix-based HTML ID generator for job monitor DOM elements."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/html_ids.ipynb.

# %% auto #0
__all__ = ['JobMonitorHtmlIds']

# %% ../nbs/html_ids.ipynb #c1000003
from dataclasses import dataclass

# %% ../nbs/html_ids.ipynb #c1000005
@dataclass
class JobMonitorHtmlIds:
    """Prefix-based HTML ID generator for job monitor DOM elements."""
    prefix: str  # ID prefix for this job monitor instance

    # --- Modal ---

    @property
    def modal(self) -> str:  # The modal dialog element
        """Modal dialog element."""
        return f"{self.prefix}-modal"

    @property
    def modal_content(self) -> str:  # Static modal body (not replaced by SSE)
        """Modal body container (holds tabs + footer, rendered once)."""
        return f"{self.prefix}-modal-content"

    @property
    def sse_connection(self) -> str:  # Hidden div that carries SSE connection
        """Hidden SSE connection element (sse-connect, receives push updates)."""
        return f"{self.prefix}-sse"

    # --- Overlay ---

    @property
    def overlay(self) -> str:  # Semi-transparent content blocker
        """Content overlay element."""
        return f"{self.prefix}-overlay"

    # --- Trigger slot ---

    @property
    def trigger_slot(self) -> str:  # Slot for trigger/progress button
        """Trigger button slot (swaps between trigger and progress button)."""
        return f"{self.prefix}-trigger-slot"

    # --- Progress ---

    @property
    def progress_bar(self) -> str:  # Progress bar element
        """Progress bar element."""
        return f"{self.prefix}-progress-bar"

    @property
    def elapsed(self) -> str:  # Elapsed time display
        """Elapsed time display element."""
        return f"{self.prefix}-elapsed"

    # --- Tabs ---

    @property
    def tabs(self) -> str:  # Tab container
        """Tab navigation container."""
        return f"{self.prefix}-tabs"

    @property
    def tab_progress(self) -> str:  # Progress tab inner content
        """Progress tab inner content (OOB target)."""
        return f"{self.prefix}-tab-progress"

    @property
    def tab_logs(self) -> str:  # Logs tab inner content
        """Logs tab inner content (OOB target)."""
        return f"{self.prefix}-tab-logs"

    @property
    def tab_resources(self) -> str:  # Resources tab inner content
        """Resources tab inner content (OOB target)."""
        return f"{self.prefix}-tab-resources"

    # --- Footer ---

    @property
    def modal_footer(self) -> str:  # Modal footer (cancel button area)
        """Modal footer (OOB target for cancel button show/hide)."""
        return f"{self.prefix}-modal-footer"

    # --- Logs ---

    @property
    def log_container(self) -> str:  # Scrollable log display
        """Log tailing container."""
        return f"{self.prefix}-log-container"
