"""Data types for job monitor URLs, configuration, and resource snapshots."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['JobMonitorUrls', 'ResourceSnapshot', 'JobMonitorConfig']

# %% ../nbs/models.ipynb #c2000003
from dataclasses import dataclass, field, asdict
from typing import Optional

# %% ../nbs/models.ipynb #c2000005
@dataclass
class JobMonitorUrls:
    """URL endpoints for the job monitor routes."""
    trigger: str   # POST -- submit job
    progress: str  # GET -- poll progress
    cancel: str    # POST -- cancel job

# %% ../nbs/models.ipynb #c2000008
@dataclass
class ResourceSnapshot:
    """Point-in-time resource usage for a worker."""
    worker_pid: int                            # Worker process ID
    cpu_percent: float                         # CPU utilization %
    memory_rss_mb: float                       # Process tree RSS in MB
    gpu_memory_mb: Optional[float] = None      # Per-process GPU memory in MB
    gpu_index: Optional[int] = None            # Which GPU device
    gpu_name: Optional[str] = None             # GPU device name
    gpu_total_mb: Optional[float] = None       # Total GPU memory in MB
    gpu_load_percent: Optional[float] = None   # GPU compute utilization %

# %% ../nbs/models.ipynb #c2000013
@dataclass
class JobMonitorConfig:
    """Configuration for a job monitor instance."""
    modal_title: str = "Job Execution"          # Modal header title
    trigger_label: str = "Run"                  # Trigger button label
    trigger_icon: Optional[str] = None          # Lucide icon name for trigger button
    progress_label: str = "View Progress"       # Progress button label (when modal closed)
    sse_interval_s: float = 0.5                 # Server-side SSE push interval in seconds
    log_lines: int = 50                         # Number of log lines to show
    overlay_z_index: int = 10                   # Overlay z-index
