"""Tabbed modal with progress, logs, and resources tabs."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/modal.ipynb.

# %% auto #0
__all__ = ['render_poll_anchor', 'render_tab_content_oob', 'render_footer_oob', 'render_poll_response', 'render_job_modal']

# %% ../../nbs/components/modal.ipynb #c9000003
from typing import Optional

from fasthtml.common import Div, H3, Button, Input, Form, Span, Dialog, FT

from cjm_fasthtml_daisyui.components.actions.modal import modal, modal_box, modal_action, modal_backdrop
from cjm_fasthtml_daisyui.components.actions.button import (
    btn, btn_colors, btn_sizes, btn_styles, btn_modifiers,
)
from cjm_fasthtml_daisyui.components.navigation.tabs import tab, tabs, tabs_styles, tab_content
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui, border_dui, text_dui
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, max_w
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, items, justify
from cjm_fasthtml_tailwind.utilities.layout import display_tw, position, right, top
from cjm_fasthtml_tailwind.core.base import combine_classes

from ..html_ids import JobMonitorHtmlIds
from ..models import JobMonitorUrls, JobMonitorConfig, ResourceSnapshot
from .tabs.progress_tab import render_progress_tab
from .tabs.logs_tab import render_logs_tab
from .tabs.resources_tab import render_resources_tab

# %% ../../nbs/components/modal.ipynb #c9000005
_TERMINAL_STATUSES = {'completed', 'failed', 'cancelled'}

def render_poll_anchor(
    ids: JobMonitorHtmlIds,       # Element IDs
    urls: JobMonitorUrls,         # Route URLs
    config: JobMonitorConfig,     # Display config
    is_active: bool = True,       # Whether polling should continue
) -> FT:  # Hidden poll anchor div
    """Render the hidden polling anchor element.
    
    When `is_active`, includes hx-get/hx-trigger for continued polling.
    When not active, renders as an inert hidden div (stops polling).
    """
    attrs = {"id": ids.poll_anchor, "style": "display:none;"}
    if is_active:
        attrs["hx_get"] = urls.progress
        attrs["hx_trigger"] = f"every {config.poll_interval_ms}ms"
        attrs["hx_swap"] = "outerHTML"
    return Div(**attrs)


def render_tab_content_oob(
    ids: JobMonitorHtmlIds,                      # Element IDs
    status: str = 'pending',                     # Job status
    progress_value: float = 0.0,                 # 0.0 to 1.0
    status_message: str = '',                    # Stage message
    started_at: Optional[float] = None,          # Unix timestamp
    completed_at: Optional[float] = None,        # Unix timestamp
    logs: str = '',                              # Log text
    resources: Optional[ResourceSnapshot] = None, # Resource data
) -> tuple:  # (progress_div, logs_div, resources_div) with OOB attrs
    """Render the three tab inner content divs as OOB swap targets."""
    progress_div = Div(
        render_progress_tab(
            ids, status=status, progress_value=progress_value,
            status_message=status_message, started_at=started_at,
            completed_at=completed_at,
        ),
        id=ids.tab_progress,
    )
    progress_div.attrs['hx-swap-oob'] = "true"

    logs_div = Div(
        render_logs_tab(ids, logs=logs),
        id=ids.tab_logs,
    )
    logs_div.attrs['hx-swap-oob'] = "true"

    resources_div = Div(
        render_resources_tab(resources),
        id=ids.tab_resources,
    )
    resources_div.attrs['hx-swap-oob'] = "true"

    return progress_div, logs_div, resources_div


def render_footer_oob(
    ids: JobMonitorHtmlIds,    # Element IDs
    urls: JobMonitorUrls,      # Route URLs
    is_active: bool = True,    # Whether job is active (show cancel)
) -> FT:  # Footer div with OOB attr
    """Render the modal footer with cancel button as OOB swap."""
    children = []
    if is_active:
        children.append(
            Button(
                "Cancel",
                hx_post=urls.cancel,
                hx_swap="none",
                cls=combine_classes(btn, btn_colors.error, btn_styles.outline, btn_sizes.sm),
            )
        )
    footer = Div(
        *children,
        id=ids.modal_footer,
        cls=combine_classes(flex_display, justify.end, m.t(4)),
    )
    footer.attrs['hx-swap-oob'] = "true"
    return footer


def render_poll_response(
    config: JobMonitorConfig,                    # Display config
    ids: JobMonitorHtmlIds,                      # Element IDs
    urls: JobMonitorUrls,                        # Route URLs
    status: str = 'pending',                     # Job status
    progress_value: float = 0.0,                 # 0.0 to 1.0
    status_message: str = '',                    # Stage message
    started_at: Optional[float] = None,          # Unix timestamp
    completed_at: Optional[float] = None,        # Unix timestamp
    logs: str = '',                              # Log text
    resources: Optional[ResourceSnapshot] = None, # Resource data
) -> tuple:  # (poll_anchor, progress_oob, logs_oob, resources_oob, footer_oob)
    """Render the poll response: updated poll anchor + OOB tab content updates.
    
    This is the primary response for the progress polling route.
    The poll anchor is the 'primary' swap target (outerHTML on itself).
    The three tab content divs and footer are OOB swaps.
    """
    is_active = status not in _TERMINAL_STATUSES

    anchor = render_poll_anchor(ids, urls, config, is_active=is_active)
    progress_div, logs_div, resources_div = render_tab_content_oob(
        ids, status=status, progress_value=progress_value,
        status_message=status_message, started_at=started_at,
        completed_at=completed_at, logs=logs, resources=resources,
    )
    footer = render_footer_oob(ids, urls, is_active=is_active)

    return (anchor, progress_div, logs_div, resources_div, footer)

# %% ../../nbs/components/modal.ipynb #c9000007
def render_job_modal(
    config: JobMonitorConfig,                    # Display config
    ids: JobMonitorHtmlIds,                      # Element IDs
    urls: JobMonitorUrls,                        # Route URLs
    status: str = 'pending',                     # Job status
    progress_value: float = 0.0,                 # 0.0 to 1.0
    status_message: str = '',                    # Stage message
    started_at: Optional[float] = None,          # Unix timestamp
    completed_at: Optional[float] = None,        # Unix timestamp
    logs: str = '',                              # Log text
    resources: Optional[ResourceSnapshot] = None, # Resource data
    open_on_render: bool = False,                # Auto-open via JS
) -> FT:  # Dialog element
    """Render the full tabbed modal dialog.
    
    The tab structure (radio inputs + tab-content wrappers) is static.
    Each tab-content wrapper contains an inner div with a stable ID
    that gets OOB-swapped by the progress route. This prevents the
    selected tab from resetting on each poll cycle.
    
    Closable via: Escape key, X button (top-right), or clicking backdrop.
    """
    is_active = status not in _TERMINAL_STATUSES
    tab_group = f"{ids.prefix}-modal-tabs"

    # Initial tab inner content
    progress_inner = render_progress_tab(
        ids, status=status, progress_value=progress_value,
        status_message=status_message, started_at=started_at,
        completed_at=completed_at,
    )
    logs_inner = render_logs_tab(ids, logs=logs)
    resources_inner = render_resources_tab(resources)

    # Tab structure — radio inputs and tab-content wrappers are static
    tab_children = [
        # Progress tab
        Input(type="radio", name=tab_group, aria_label="Progress",
              checked="checked", cls=str(tab)),
        Div(
            Div(progress_inner, id=ids.tab_progress),
            cls=combine_classes(tab_content, border_dui.base_300, bg_dui.base_100),
        ),
        # Logs tab
        Input(type="radio", name=tab_group, aria_label="Logs", cls=str(tab)),
        Div(
            Div(logs_inner, id=ids.tab_logs),
            cls=combine_classes(tab_content, border_dui.base_300, bg_dui.base_100),
        ),
        # Resources tab
        Input(type="radio", name=tab_group, aria_label="Resources", cls=str(tab)),
        Div(
            Div(resources_inner, id=ids.tab_resources),
            cls=combine_classes(tab_content, border_dui.base_300, bg_dui.base_100),
        ),
    ]

    tab_container = Div(
        *tab_children,
        cls=combine_classes(tabs, tabs_styles.border, w.full),
    )

    # Footer with cancel button
    footer_children = []
    if is_active:
        footer_children.append(
            Button(
                "Cancel",
                hx_post=urls.cancel,
                hx_swap="none",
                cls=combine_classes(btn, btn_colors.error, btn_styles.outline, btn_sizes.sm),
            )
        )
    footer = Div(
        *footer_children,
        id=ids.modal_footer,
        cls=combine_classes(flex_display, justify.end, m.t(4)),
    )

    # Poll anchor (hidden, drives HTMX polling)
    poll = render_poll_anchor(ids, urls, config, is_active=is_active)

    # X close button (top-right corner)
    close_btn = Form(
        Button(
            "\u2715",  # Unicode multiplication sign (✕)
            cls=combine_classes(
                btn, btn_sizes.sm, btn_modifiers.circle, btn_styles.ghost,
                position.absolute, right._2, top._2,
            ),
        ),
        method="dialog",
    )

    # Open script
    from fasthtml.common import Script
    open_script = Script(
        f"document.getElementById('{ids.modal}').showModal();"
    ) if open_on_render else Span()

    return Dialog(
        Div(
            # X close button
            close_btn,
            # Header
            H3(config.modal_title, cls=combine_classes(font_weight.bold, font_size.lg)),
            # Tab structure (static)
            tab_container,
            # Footer (OOB-swappable)
            footer,
            # Poll anchor (hidden)
            poll,
            cls=combine_classes(modal_box, max_w._2xl, w.full),
        ),
        # Backdrop — clicking outside closes the modal
        Form(Button("close", cls=combine_classes(btn, btn_styles.ghost)), method="dialog", cls=str(modal_backdrop)),
        open_script,
        id=ids.modal,
        cls=str(modal),
    )
