"""Tabbed modal with progress, logs, and resources tabs."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/modal.ipynb.

# %% auto #0
__all__ = ['render_sse_connection', 'render_tab_content_oob', 'render_footer_oob', 'render_sse_response', 'get_sse_headers',
           'render_job_modal']

# %% ../../nbs/components/modal.ipynb #c9000003
from typing import Optional, List

from fasthtml.common import Div, H3, Button, Input, Form, Span, Dialog, Script, FT

from cjm_fasthtml_daisyui.components.actions.modal import modal, modal_box, modal_action, modal_backdrop
from cjm_fasthtml_daisyui.components.actions.button import btn_modifiers
from cjm_fasthtml_daisyui.components.navigation.tabs import tab, tabs, tabs_styles, tab_content
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui, border_dui, text_dui
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, max_w
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, items, justify
from cjm_fasthtml_tailwind.utilities.layout import display_tw, position, right, top
from cjm_fasthtml_tailwind.core.base import combine_classes

# Design system recipes (V1 button roles)
from cjm_fasthtml_design_system.buttons import buttons

from ..html_ids import JobMonitorHtmlIds
from ..models import JobMonitorUrls, JobMonitorConfig, ResourceSnapshot
from .tabs.progress_tab import render_progress_tab
from .tabs.logs_tab import render_logs_tab
from .tabs.resources_tab import render_resources_tab

# %% ../../nbs/components/modal.ipynb #c9000005
_TERMINAL_STATUSES = {'completed', 'failed', 'cancelled'}

def render_sse_connection(
    ids: JobMonitorHtmlIds,       # Element IDs
    urls: JobMonitorUrls,         # Route URLs (progress URL used for SSE endpoint)
    job_id: str,                  # Active job ID (passed as query param)
    is_active: bool = True,       # Whether SSE should be connected
) -> FT:  # Hidden SSE connection div
    """Render the hidden SSE connection element.
    
    When `is_active`, includes hx-ext=sse and sse-connect for real-time updates.
    When not active, renders as an inert hidden div (no connection).
    """
    attrs = {"id": ids.sse_connection, "style": "display:none;"}
    if is_active and job_id:
        attrs["hx_ext"] = "sse"
        attrs["sse_connect"] = f"{urls.progress}?job_id={job_id}"
        attrs["sse_swap"] = "message"
        attrs["hx_swap"] = "none"
    return Div(**attrs)


def render_tab_content_oob(
    ids: JobMonitorHtmlIds,                      # Element IDs
    status: str = 'pending',                     # Job status
    progress_value: float = 0.0,                 # 0.0 to 1.0
    status_message: str = '',                    # Stage message
    started_at: Optional[float] = None,          # Unix timestamp
    completed_at: Optional[float] = None,        # Unix timestamp
    logs: str = '',                              # Log text
    resources: Optional[ResourceSnapshot] = None, # Resource data
) -> tuple:  # (progress_div, logs_div, resources_div) with OOB attrs
    """Render the three tab inner content divs as OOB swap targets."""
    progress_div = Div(
        render_progress_tab(
            ids, status=status, progress_value=progress_value,
            status_message=status_message, started_at=started_at,
            completed_at=completed_at,
        ),
        id=ids.tab_progress,
    )
    progress_div.attrs['hx-swap-oob'] = "true"

    logs_div = Div(
        render_logs_tab(ids, logs=logs),
        id=ids.tab_logs,
    )
    logs_div.attrs['hx-swap-oob'] = "true"

    resources_div = Div(
        render_resources_tab(resources),
        id=ids.tab_resources,
    )
    resources_div.attrs['hx-swap-oob'] = "true"

    return progress_div, logs_div, resources_div


def render_footer_oob(
    ids: JobMonitorHtmlIds,    # Element IDs
    urls: JobMonitorUrls,      # Route URLs
    is_active: bool = True,    # Whether job is active (show cancel)
) -> FT:  # Footer div with OOB attr
    """Render the modal footer with cancel button as OOB swap."""
    children = []
    if is_active:
        children.append(
            Button(
                "Cancel",
                hx_post=urls.cancel,
                hx_swap="none",
                cls=buttons.destructive_cancellable,
            )
        )
    footer = Div(
        *children,
        id=ids.modal_footer,
        cls=combine_classes(flex_display, justify.end, m.t(4)),
    )
    footer.attrs['hx-swap-oob'] = "true"
    return footer


def _make_tab_oob(ids, tab_id, render_fn, *args, **kwargs):
    """Render a single tab's inner content as OOB swap target."""
    div = Div(render_fn(*args, **kwargs), id=tab_id)
    div.attrs['hx-swap-oob'] = "true"
    return div


def render_sse_response(
    ids: JobMonitorHtmlIds,                      # Element IDs
    urls: JobMonitorUrls,                        # Route URLs
    status: str = 'pending',                     # Job status
    progress_value: float = 0.0,                 # 0.0 to 1.0
    status_message: str = '',                    # Stage message
    started_at: Optional[float] = None,          # Unix timestamp
    completed_at: Optional[float] = None,        # Unix timestamp
    logs: Optional[str] = None,                  # Log text (None = skip logs tab update)
    resources: Optional[ResourceSnapshot] = None, # Resource data (None = skip resources tab update)
    include_footer: bool = False,                # Include footer OOB (only needed on state transitions)
    extra_oob: Optional[List[FT]] = None,        # Additional OOB elements (cleanup, callbacks)
) -> FT:  # Div wrapping all OOB elements for sse_message()
    """Build the OOB update payload for an SSE push.
    
    Selectively includes only changed elements:
    - Progress tab: always included (status/progress/elapsed change frequently)
    - Logs tab: included only when `logs` is not None
    - Resources tab: included only when `resources` is not None
    - Footer: included only when `include_footer` is True (state transitions)
    """
    is_active = status not in _TERMINAL_STATUSES
    children = []

    # Progress tab — always
    children.append(_make_tab_oob(
        ids, ids.tab_progress, render_progress_tab,
        ids, status=status, progress_value=progress_value,
        status_message=status_message, started_at=started_at,
        completed_at=completed_at,
    ))

    # Logs tab — only if logs provided
    if logs is not None:
        children.append(_make_tab_oob(
            ids, ids.tab_logs, render_logs_tab,
            ids, logs=logs,
        ))

    # Resources tab — only if resources provided
    if resources is not None:
        children.append(_make_tab_oob(
            ids, ids.tab_resources, render_resources_tab,
            resources,
        ))

    # Footer — only on state transitions
    if include_footer:
        children.append(render_footer_oob(ids, urls, is_active=is_active))

    if extra_oob:
        children.extend(extra_oob)

    return Div(*children)


def get_sse_headers() -> List[FT]:
    """Return the HTMX SSE extension script + cleanup script for app headers.
    
    Consumers should add these to their FastHTML app's hdrs list.
    The SSE extension must load after the main HTMX script.
    """
    return [
        Script(src="https://unpkg.com/htmx-ext-sse@2.2.2"),
        Script("window.addEventListener('beforeunload',()=>{"
               "document.querySelectorAll('[sse-connect]').forEach(e=>{"
               "const d=e['htmx-internal-data'];if(d&&d.sseEventSource)d.sseEventSource.close();"
               "})});"),
    ]

# %% ../../nbs/components/modal.ipynb #c9000007
def render_job_modal(
    config: JobMonitorConfig,                    # Display config
    ids: JobMonitorHtmlIds,                      # Element IDs
    urls: JobMonitorUrls,                        # Route URLs
    job_id: str = '',                            # Active job ID for SSE connection
    status: str = 'pending',                     # Job status
    progress_value: float = 0.0,                 # 0.0 to 1.0
    status_message: str = '',                    # Stage message
    started_at: Optional[float] = None,          # Unix timestamp
    completed_at: Optional[float] = None,        # Unix timestamp
    logs: str = '',                              # Log text
    resources: Optional[ResourceSnapshot] = None, # Resource data
    open_on_render: bool = False,                # Auto-open via JS
) -> FT:  # Dialog element
    """Render the full tabbed modal dialog.
    
    The tab structure (radio inputs + tab-content wrappers) is static.
    Each tab-content wrapper contains an inner div with a stable ID
    that gets OOB-swapped by the SSE stream. This prevents the
    selected tab from resetting on each update.
    
    Closable via: Escape key, X button (top-right), or clicking backdrop.
    """
    is_active = status not in _TERMINAL_STATUSES
    tab_group = f"{ids.prefix}-modal-tabs"

    # Initial tab inner content
    progress_inner = render_progress_tab(
        ids, status=status, progress_value=progress_value,
        status_message=status_message, started_at=started_at,
        completed_at=completed_at,
    )
    logs_inner = render_logs_tab(ids, logs=logs)
    resources_inner = render_resources_tab(resources)

    # Tab structure — radio inputs and tab-content wrappers are static
    tab_children = [
        # Progress tab
        Input(type="radio", name=tab_group, aria_label="Progress",
              checked="checked", cls=str(tab)),
        Div(
            Div(progress_inner, id=ids.tab_progress),
            cls=combine_classes(tab_content, border_dui.base_300, bg_dui.base_100),
        ),
        # Logs tab
        Input(type="radio", name=tab_group, aria_label="Logs", cls=str(tab)),
        Div(
            Div(logs_inner, id=ids.tab_logs),
            cls=combine_classes(tab_content, border_dui.base_300, bg_dui.base_100),
        ),
        # Resources tab
        Input(type="radio", name=tab_group, aria_label="Resources", cls=str(tab)),
        Div(
            Div(resources_inner, id=ids.tab_resources),
            cls=combine_classes(tab_content, border_dui.base_300, bg_dui.base_100),
        ),
    ]

    tab_container = Div(
        *tab_children,
        cls=combine_classes(tabs, tabs_styles.border, w.full),
    )

    # Footer with cancel button
    footer_children = []
    if is_active:
        footer_children.append(
            Button(
                "Cancel",
                hx_post=urls.cancel,
                hx_swap="none",
                cls=buttons.destructive_cancellable,
            )
        )
    footer = Div(
        *footer_children,
        id=ids.modal_footer,
        cls=combine_classes(flex_display, justify.end, m.t(4)),
    )

    # SSE connection (hidden, drives real-time updates)
    sse_el = render_sse_connection(ids, urls, job_id, is_active=is_active)

    # X close button (top-right corner)
    close_btn = Form(
        Button(
            "✕",  # Unicode multiplication sign
            cls=combine_classes(
                buttons.soft_dismissal, btn_modifiers.circle,
                position.absolute, right._2, top._2,
            ),
        ),
        method="dialog",
    )

    # Open script
    open_script = Script(
        f"document.getElementById('{ids.modal}').showModal();"
    ) if open_on_render else Span()

    return Dialog(
        Div(
            # X close button
            close_btn,
            # Header
            H3(config.modal_title, cls=combine_classes(font_weight.bold, font_size.lg)),
            # Tab structure (static)
            tab_container,
            # Footer (OOB-swappable)
            footer,
            # SSE connection (hidden)
            sse_el,
            cls=combine_classes(modal_box, max_w._2xl, w.full),
        ),
        # Backdrop — plain unstyled button per DaisyUI v5 pattern
        Form(Button("close"), method="dialog", cls=str(modal_backdrop)),
        open_script,
        id=ids.modal,
        cls=str(modal),
    )
