"""Semi-transparent content overlay with loading spinner."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/overlay.ipynb.

# %% auto #0
__all__ = ['render_job_overlay', 'render_job_overlay_placeholder']

# %% ../../nbs/components/overlay.ipynb #c5000003
from fasthtml.common import Div, Span, FT

from cjm_fasthtml_daisyui.components.feedback.loading import loading, loading_styles, loading_sizes
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui
from cjm_fasthtml_tailwind.utilities.layout import position, inset, z, display_tw
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, items, justify
from cjm_fasthtml_tailwind.utilities.borders import rounded
from cjm_fasthtml_tailwind.utilities.effects import opacity
from cjm_fasthtml_tailwind.core.base import combine_classes

from ..html_ids import JobMonitorHtmlIds
from ..models import JobMonitorConfig

# %% ../../nbs/components/overlay.ipynb #c5000005
def render_job_overlay(
    ids: JobMonitorHtmlIds,       # Element IDs
    config: JobMonitorConfig,     # Display config (for z-index)
) -> FT:  # Overlay div with centered spinner
    """Render semi-transparent overlay with loading spinner."""
    return Div(
        Span(cls=combine_classes(loading, loading_styles.spinner, loading_sizes.lg)),
        id=ids.overlay,
        cls=combine_classes(
            position.absolute, inset(0), z(config.overlay_z_index),
            flex_display, items.center, justify.center,
            bg_dui.base_300, opacity(50),
            rounded.lg,
        ),
    )

# %% ../../nbs/components/overlay.ipynb #c5000008
def render_job_overlay_placeholder(
    ids: JobMonitorHtmlIds,  # Element IDs
) -> FT:  # Empty div with overlay ID (display:none)
    """Render empty placeholder (swapping this in removes the overlay).

    The placeholder has `display:none` so it contributes no layout
    (no flex gap slot, no grid track) to the overlay target's layout tree.
    The active `render_job_overlay` uses `position: absolute` for the same
    guarantee; both states keep the overlay container structurally invisible.
    """
    return Div(
        id=ids.overlay,
        cls=combine_classes(display_tw.hidden),
    )
