"""Trigger button and progress button for job monitor."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/trigger.ipynb.

# %% auto #0
__all__ = ['render_job_trigger', 'render_job_progress_button']

# %% ../../nbs/components/trigger.ipynb #c4000003
from typing import Optional

from fasthtml.common import Div, Button, Span, Script, FT

from cjm_fasthtml_daisyui.components.actions.button import btn, btn_colors, btn_sizes, btn_styles
from cjm_fasthtml_daisyui.components.feedback.loading import loading, loading_styles, loading_sizes
from cjm_fasthtml_tailwind.utilities.spacing import m
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, items, gap
from cjm_fasthtml_tailwind.core.base import combine_classes

from ..html_ids import JobMonitorHtmlIds
from ..models import JobMonitorUrls, JobMonitorConfig

# %% ../../nbs/components/trigger.ipynb #c4000005
def render_job_trigger(
    config: JobMonitorConfig,     # Display config
    ids: JobMonitorHtmlIds,       # Element IDs
    urls: JobMonitorUrls,         # Route URLs
    disabled: bool = False,       # Disable button
    icon_fn: Optional[callable] = None,  # Icon renderer fn(name, **kwargs) -> FT
) -> FT:  # Trigger button wrapped in slot div
    """Render the initial trigger button."""
    btn_children = []
    if config.trigger_icon and icon_fn:
        btn_children.append(icon_fn(config.trigger_icon, size=4))
    btn_children.append(Span(config.trigger_label))

    return Div(
        Button(
            *btn_children,
            hx_post=urls.trigger,
            hx_swap="none",
            disabled=disabled,
            cls=combine_classes(
                btn, btn_styles.outline, btn_sizes.sm,
                flex_display, items.center, gap(1),
            ),
        ),
        id=ids.trigger_slot,
    )

# %% ../../nbs/components/trigger.ipynb #c4000009
def render_job_progress_button(
    config: JobMonitorConfig,   # Display config
    ids: JobMonitorHtmlIds,     # Element IDs
) -> FT:  # Progress button wrapped in slot div
    """Render 'View Progress' button with spinner."""
    return Div(
        Button(
            Span(cls=combine_classes(loading, loading_styles.spinner, loading_sizes.xs)),
            Span(config.progress_label),
            type="button",  # Prevent form submission when inside StepFlow form wrapper
            onclick=f"document.getElementById('{ids.modal}').showModal()",
            cls=combine_classes(
                btn, btn_colors.primary, btn_sizes.sm,
                flex_display, items.center, gap(1),
            ),
        ),
        id=ids.trigger_slot,
    )
