"""Service for job execution monitoring with resource telemetry."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/services/monitor.ipynb.

# %% auto #0
__all__ = ['JobMonitorService']

# %% ../../nbs/services/monitor.ipynb #c3000003
from typing import Any, Dict, List, Optional, Tuple

from cjm_plugin_system.core.queue import JobQueue, Job, JobStatus
from cjm_plugin_system.core.manager import PluginManager

from ..models import ResourceSnapshot

# %% ../../nbs/services/monitor.ipynb #c3000005
class JobMonitorService:
    """Service for job execution monitoring with resource telemetry."""

    def __init__(
        self,
        queue: JobQueue,                          # Job queue instance
        manager: PluginManager,                   # For worker stats, logs, sysmon
        sysmon_plugin_name: Optional[str] = None, # System monitor plugin name (e.g., 'cjm-system-monitor-nvidia')
    ):
        self._queue = queue
        self._manager = manager
        self._sysmon_name = sysmon_plugin_name

# %% ../../nbs/services/monitor.ipynb #c3000007
async def _submit_job(
    self,
    plugin_name: str,       # Target plugin
    *args,
    priority: int = 0,
    **kwargs
) -> str:  # job_id
    """Submit a job to the queue."""
    return await self._queue.submit(plugin_name, *args, priority=priority, **kwargs)

def _get_job(self, job_id: str) -> Optional[Job]:  # Job or None
    """Get job by ID."""
    return self._queue.get_job(job_id)

async def _cancel_job(self, job_id: str) -> bool:  # True if cancelled
    """Cancel a job."""
    return await self._queue.cancel(job_id)

JobMonitorService.submit_job = _submit_job
JobMonitorService.get_job = _get_job
JobMonitorService.cancel_job = _cancel_job

# %% ../../nbs/services/monitor.ipynb #c3000009
def _get_logs(
    self,
    plugin_name: str,              # Plugin whose logs to read
    lines: int = 50,               # Max lines to return
    current_session_only: bool = True,  # Filter to current session
) -> str:  # Log text
    """Get plugin logs, optionally filtered to current session."""
    # Read extra lines so session filtering has enough to work with
    read_lines = lines * 3 if current_session_only else lines
    raw = self._manager.get_plugin_logs(plugin_name, lines=read_lines)
    if current_session_only:
        return _filter_current_session(raw, lines)
    return raw

JobMonitorService.get_logs = _get_logs

# %% ../../nbs/services/monitor.ipynb #c3000010
def _filter_current_session(
    raw: str,        # Full log text
    max_lines: int,  # Max lines to return
) -> str:  # Filtered log text
    """Extract logs from the most recent session (after last '--- Starting' marker)."""
    all_lines = raw.split('\n')
    last_marker = -1
    for i, line in enumerate(all_lines):
        if line.strip().startswith('--- Starting'):
            last_marker = i
    if last_marker >= 0:
        session_lines = all_lines[last_marker + 1:]
    else:
        session_lines = all_lines
    # Strip trailing empty lines
    while session_lines and not session_lines[-1].strip():
        session_lines.pop()
    return '\n'.join(session_lines[-max_lines:])

# %% ../../nbs/services/monitor.ipynb #c3000015
def _get_resource_snapshot(
    self,
    plugin_name: str,  # Plugin whose worker to query
) -> Optional[ResourceSnapshot]:  # Snapshot or None
    """Get current resource usage for a plugin's worker."""
    proxy = self._manager.get_plugin(plugin_name)
    if not proxy or not hasattr(proxy, 'get_stats'):
        return None

    try:
        stats = proxy.get_stats()
    except Exception:
        return None

    snapshot = ResourceSnapshot(
        worker_pid=stats.get('pid', 0),
        cpu_percent=stats.get('cpu_percent', 0.0),
        memory_rss_mb=stats.get('memory_rss_mb', 0.0),
    )

    # Enrich with GPU stats from system monitor
    _enrich_gpu_stats(self, snapshot)
    return snapshot

JobMonitorService.get_resource_snapshot = _get_resource_snapshot

# %% ../../nbs/services/monitor.ipynb #c3000016
def _enrich_gpu_stats(
    self,
    snapshot: ResourceSnapshot,  # Snapshot to enrich in place
) -> None:
    """Add per-process GPU stats from system monitor plugin."""
    if not self._sysmon_name:
        return

    sysmon = self._manager.get_plugin(self._sysmon_name)
    if not sysmon:
        return

    try:
        sys_stats = sysmon.execute("get_system_status")
    except Exception:
        return

    details = sys_stats.get('details', {})
    processes = details.get('processes', [])

    # Find GPU process matching worker PID
    for proc in processes:
        if proc.get('pid') == snapshot.worker_pid:
            snapshot.gpu_memory_mb = proc.get('gpu_memory_mb', 0.0)
            snapshot.gpu_index = proc.get('gpu_index')
            break

    # Add global GPU info for context
    gpu_details = details.get('details', {})
    if snapshot.gpu_index is not None:
        gpu_key = f'gpu_{snapshot.gpu_index}'
        gpu = gpu_details.get(gpu_key, {})
        snapshot.gpu_name = gpu.get('name')
        snapshot.gpu_total_mb = gpu.get('memory_total')
        snapshot.gpu_load_percent = gpu.get('utilization')

JobMonitorService._enrich_gpu_stats = _enrich_gpu_stats
