"""Log tailing view with auto-scroll."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/tabs/logs_tab.ipynb.

# %% auto #0
__all__ = ['render_logs_tab']

# %% ../../../nbs/components/tabs/logs_tab.ipynb #c7000003
from fasthtml.common import Div, Pre, Code, Script, FT

from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui, text_dui
from cjm_fasthtml_tailwind.utilities.spacing import p
from cjm_fasthtml_tailwind.utilities.sizing import max_h, w
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_family
from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.utilities.borders import rounded
from cjm_fasthtml_tailwind.core.base import combine_classes

from ...html_ids import JobMonitorHtmlIds

# %% ../../../nbs/components/tabs/logs_tab.ipynb #c7000005
def render_logs_tab(
    ids: JobMonitorHtmlIds,  # Element IDs
    logs: str = '',          # Log text content
) -> FT:  # Logs tab content
    """Render logs tab with auto-scroll to bottom."""
    return Div(
        Pre(
            Code(logs or 'No logs available.'),
            id=ids.log_container,
            cls=combine_classes(
                bg_dui.base_200, rounded.lg, p(3),
                max_h(64), overflow.y.auto, w.full,
                font_size.xs, font_family.mono, text_dui.base_content,
            ),
        ),
        # Auto-scroll to bottom on each update
        Script(f"""
        requestAnimationFrame(() => {{
            const el = document.getElementById('{ids.log_container}');
            if (el) el.scrollTop = el.scrollHeight;
        }});
        """),
        cls=p(4),
    )
