"""Worker CPU, RAM, and GPU resource usage display."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/tabs/resources_tab.ipynb.

# %% auto #0
__all__ = ['render_resources_tab']

# %% ../../../nbs/components/tabs/resources_tab.ipynb #c8000003
from typing import Optional

from fasthtml.common import Div, Span, Progress, FT

from cjm_fasthtml_daisyui.components.feedback.progress import progress as progress_cls, progress_colors
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui, bg_dui
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, h
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight, font_family
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, items, justify, gap
from cjm_fasthtml_tailwind.core.base import combine_classes

from ...models import ResourceSnapshot

# %% ../../../nbs/components/tabs/resources_tab.ipynb #c8000005
def _render_stat_row(
    label: str,          # Stat label (e.g., 'CPU')
    value_text: str,     # Formatted value (e.g., '45.2%')
    bar_pct: Optional[int] = None,   # Progress bar percentage (0-100)
    bar_color: str = '',             # DaisyUI progress color class
) -> FT:  # Stat row element
    """Render a single stat row with label, value, and optional progress bar."""
    children = [
        Div(
            Span(label, cls=combine_classes(font_size.xs, text_dui.base_content)),
            Span(value_text, cls=combine_classes(font_size.xs, font_weight.semibold, font_family.mono)),
            cls=combine_classes(flex_display, items.center, justify.between),
        ),
    ]
    if bar_pct is not None:
        children.append(
            Progress(
                value=str(max(0, min(100, bar_pct))),
                max="100",
                cls=combine_classes(progress_cls, bar_color, w.full, h(1)),
            )
        )
    return Div(*children, cls=m.b(3))

# %% ../../../nbs/components/tabs/resources_tab.ipynb #c8000007
def render_resources_tab(
    resources: Optional[ResourceSnapshot] = None,  # Resource data
) -> FT:  # Resources tab content
    """Render resources tab content."""
    if resources is None:
        return Div(
            Span('No resource data available.', cls=combine_classes(font_size.sm, text_dui.base_content)),
            cls=p(4),
        )

    children = []

    # Worker PID
    children.append(
        Div(
            Span('Worker PID: ', cls=combine_classes(font_size.xs, text_dui.base_content)),
            Span(str(resources.worker_pid), cls=combine_classes(font_size.xs, font_weight.semibold, font_family.mono)),
            cls=m.b(3),
        )
    )

    # CPU
    children.append(_render_stat_row(
        label='CPU',
        value_text=f'{resources.cpu_percent:.1f}%',
        bar_pct=int(resources.cpu_percent),
        bar_color=str(progress_colors.info),
    ))

    # Memory RSS
    children.append(_render_stat_row(
        label='Memory (RSS)',
        value_text=f'{resources.memory_rss_mb:.0f} MB',
    ))

    # GPU section (if available)
    if resources.gpu_memory_mb is not None:
        # GPU name header
        gpu_label = resources.gpu_name or f'GPU {resources.gpu_index}'
        children.append(
            Div(
                Span(gpu_label, cls=combine_classes(font_size.xs, font_weight.semibold, text_dui.base_content)),
                cls=combine_classes(m.t(2), m.b(1)),
            )
        )

        # GPU memory
        gpu_pct = None
        gpu_value = f'{resources.gpu_memory_mb:.0f} MB'
        if resources.gpu_total_mb and resources.gpu_total_mb > 0:
            gpu_pct = int((resources.gpu_memory_mb / resources.gpu_total_mb) * 100)
            gpu_value = f'{resources.gpu_memory_mb:.0f} / {resources.gpu_total_mb:.0f} MB'

        children.append(_render_stat_row(
            label='GPU Memory',
            value_text=gpu_value,
            bar_pct=gpu_pct,
            bar_color=str(progress_colors.secondary),
        ))

        # GPU load
        if resources.gpu_load_percent is not None:
            children.append(_render_stat_row(
                label='GPU Load',
                value_text=f'{resources.gpu_load_percent:.0f}%',
                bar_pct=int(resources.gpu_load_percent),
                bar_color=str(progress_colors.secondary),
            ))

    return Div(*children, cls=p(4))
